CREATE TABLE users(
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL
);

CREATE TABLE apps(
  app_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  author_id TEXT NOT NULL,
  description TEXT NOT NULL,
  streaming INTEGER NOT NULL,
  stream_endpoint TEXT,
  frontend_ip TEXT,
  FOREIGN KEY(author_id) REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE permissions(
  app_id INTEGER NOT NULL PRIMARY KEY,
  Acceleration INTEGER NOT NULL,
  Battery INTEGER NOT NULL,
  Doors INTEGER NOT NULL,
  Engine_Information INTEGER NOT NULL,
  Engine_Utilization INTEGER NOT NULL,
  Fuel_Information INTEGER NOT NULL,
  Gyroscope INTEGER NOT NULL,
  HVAC INTEGER NOT NULL,
  Hood INTEGER NOT NULL,
  Lights INTEGER NOT NULL,
  Mirrors INTEGER NOT NULL,
  Parking_Brake INTEGER NOT NULL,
  Pedal_Positions INTEGER NOT NULL,
  Position_Information INTEGER NOT NULL,
  Seat_Belts INTEGER NOT NULL,
  Speed INTEGER NOT NULL,
  Torque INTEGER NOT NULL,
  Trunk INTEGER NOT NULL,
  Vehicle_Turning INTEGER NOT NULL,
  Windows INTEGER NOT NULL,
  Windshield_Wipers INTEGER NOT NULL,
  FOREIGN KEY(app_id) REFERENCES apps ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE vehicles(
    vehicle_id TEXT PRIMARY KEY,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    year INTEGER NOT NULL,
    dbc INTEGER NOT NULL
);

CREATE TABLE traces(
    trace_id INTEGER PRIMARY KEY AUTOINCREMENT,
    vehicle_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    app_id INTEGER,
    FOREIGN KEY(vehicle_id) REFERENCES vehicles ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(user_id) REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(app_id) REFERENCES apps ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE developer_messages(
    app_id INTEGER NOT NULL PRIMARY KEY,
    message TEXT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(app_id) REFERENCES apps ON UPDATE CASCADE ON DELETE CASCADE
);